spring:
  application:
    name: gateway-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-container:8080/realms/master/protocol/openid-connect/certs
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-container
    port: 5672

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-server-container:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: UNRESTRICTED

logging:
  level:
    org.springframework.gateway: DEBUG
    org.springframework.security: DEBUG