server:
  port: 8082
spring:
  application:
    name: cards-service
  datasource:
    url: jdbc:mysql://localhost:3306/cardsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: qa