spring:
  application:
    name: discovery-server
  rabbitmq:
    host: rabbitmq-container
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"

