spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Naveen-HC/Digital-Banking-Microservices-Config
          force-pull: true
          clone-on-start: true
  rabbitmq:
    host: rabbitmq-container
    username: guest
    password: guest
    port: 5672

server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true